language: python

python:
  - '3.5.2'

cache: pip

services:
  - mysql

env:
  global:
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=1.10 DB=mysql

install:
  - pip install django==1.10
  - pip install requests
  - pip install django-mysql
  - pip install mysqlclient

branches:
  only:
  - master

before_script:
  - mysql -e 'create database travis_ci_db;'
  - python ./models/manage.py migrate
  - python ./models/manage.py makemigrations

script:
  - python ./models/manage.py test api.tests