language: python

python:
  - '3.5.2'

cache: pip

services:
  - mysql

env:
  global:
    - PYTHONPATH="/home/travis/build/bwz3kt/cs4501_project"
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=1.10 DB=mysql

install:
  - pip install django==1.10
  - pip install selenium
  - pip install requests
  - pip install django-mysql
  - pip install mysqlclient

branches:
  only:
  - master

before_script:
  - mysql -e 'create database travis_ci_db;'
  - python manage.py syncdb --noinput

script:
  - python ./models/manage.py test api.tests
  - python ./selenium/selenium_script.py