language: python

python:
  - '3.5.2'

cache: pip

install:
  - pip install django==1.10
  - pip install selenium
  - pip install requests
  - pip install django-mysql

branches:
  only:
  - master

script:
  - python ./models/manage.py test
  - python ./selenium/selenium_script.py