models:
  image: tp33/django
  container_name: proj_models
  external_links:
    - mysql:db
  volumes:
    - .:/app
  ports:
    - "8001:8000"
  command: bash -c "pip install django-mysql && python /app/models/manage.py makemigrations api && python /app/models/manage.py migrate && python /app/models/manage.py loaddata /app/models/db.json && python /app/models/manage.py test api && mod_wsgi-express start-server --working-directory /app/models --reload-on-changes /app/models/models/wsgi.py"

exp:
  image: tp33/django
  container_name: proj_exp
  links:
      - models:models-api
  ports:
      - "8002:8000"
  volumes:
      - .:/app
  command: bash -c "pip install requests && mod_wsgi-express start-server --working-directory /app/exp --reload-on-changes /app/exp/exp/wsgi.py"

web:
  container_name: proj_web
  image: tp33/django
  links:
      - exp:exp-api
  ports:
      - "8000:8000"
  volumes:
      - .:/app
  command: bash -c "pip install requests && mod_wsgi-express start-server --working-directory /app/web --reload-on-changes --log-to-terminal /app/web/web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"
